### ISSUE TITLE
no docs for populating supabase

### ISSUE THREAD

**Issue by ishowvel** [ubiquity-os-marketplace/command-wallet#20]
There is nothing in the readme as of right now which might give a hint on populating the tables in supabase, this might be a headache for first time contributors

**Comment by ishowvel** [comment]
@0x4007 can you give your views on this.
there is nothing that clearly states how supabase should be set up. following the steps in the readme will result in a table not found error when a user tries to add their wallet using /wallet.

**Comment by 0x4007** [comment]
@gentlementlegen @Whilefoo might know more here

**Comment by 0x4007** [comment]
@UbiquityOS explain as clearly and concisely as possible on how to set up supabase for this plugin for a first time contributor.

**Comment by 0x4007** [comment]
Not sure how accurate this is but most of it seems to check out

**Comment by gentlementlegen** [comment]
@ishowvel You can refer to https://github.com/ubiquity-os/database to set up your own Supabase instance, should just be a matter of cloning and `supabase start`.

**Comment by ishowvel** [comment]
It would have been really helpful if it was linked 😭😭😭

**Comment by gentlementlegen** [comment]
We created this repository 2 days ago because we noticed the database was still located within the old bot. I'll add the link in the readme.
