### ISSUE TITLE
December 2024 Fixes

### ISSUE THREAD

**Issue by 0x4007** [ubiquity-os-marketplace/command-wallet#28]
Registration failures makes the system unusable. 

# Unnecessary Error

The previous error above it is sufficient this one should not display to the user. 

```diff
! Error: Error: No wallet address found
```

_Originally posted by @ubiquity-os[bot] in https://github.com/ubiquity/business-development/issues/85#issuecomment-2516869446_

# Registration Failure
            
```diff
! Error: [object Object]
```

_Originally posted by @ubiquity-os[bot] in https://github.com/ubiquity/business-development/issues/85#issuecomment-2516896879_

**Comment by gentlementlegen** [comment]
Another instance of the error: https://github.com/ubiquity-os/plugins-wishlist/issues/31#issuecomment-2516904249

**Comment by gentlementlegen** [comment]
The `! Error: Error: No wallet address found` comes from command start stop not this plugin I think.

**Comment by gentlementlegen** [comment]
Link to the error in CF: https://dash.cloudflare.com/17b9dfa79e16b79dffcb11a66768539c/workers/services/view/ubiquity-os-command-wallet-main/production/observability/logs?granularity=0&time=%7B%22type%22%3A%22absolute%22%2C%22to%22%3A1733308320000%2C%22from%22%3A1733308200000%7D

The error is the following:
```
[33m	⚠ {
	    "err": {
	      "code": "23505",
	      "details": "Key (address)=(0xB13260bfEe08DcA208F2ECc735171B21763EaaF6) already exists.",
	      "hint": null,
	      "message": "duplicate key value violates unique constraint \"new_wallets_wallet_key\""
	    },
	    "caller": "plugin"
	  }[0m
```

I believe the main problem is the error display that is wrong (should give this instead of [Object object]).

**Comment by 0x4007** [comment]
I see that's interesting. It's hard to say what's the right answer but I think we should not support sybils. To use the system you should only be using one GitHub account. There will be an incentive to use a single account when we have XP one day.

**Comment by gentlementlegen** [comment]
Well that's the think I don't think there is any way to "unset" wallets at this time. We could also implement that. I don't think it's a very common use case, only if you use multiple accounts or somehow lost your account and you use a new one? Here is a complete error for a duplicated account: https://github.com/Meniole/command-wallet/issues/5#issuecomment-2522529468

So I'd say either we allow multiple accounts linked to one wallet, either we offer a way to unset wallets from an account.

**Comment by 0x4007** [comment]
It's useful for us to know who is a sybil. Maybe unsetting can be like

/wallet null

**Comment by gentlementlegen** [comment]
Okay then I would suggest something like `/wallet - -unset` to avoid ambiguity with domain names.

**Comment by gentlementlegen** [comment]
For some reasons it seems that @whilefoo comments didn't get picked up here? I will have a look.

**Comment by 0x4007** [comment]
They have had problems registering their wallet in the past so that may also be related. 

Lastly we still need to adjust the algorithm to not take a baseline from the formatting score. If relevance is 0 then the final score should be 0

**Comment by gentlementlegen** [comment]
@0x4007 That change was made after your request: https://github.com/ubiquity-os-marketplace/text-conversation-rewards/issues/92#issuecomment-2357720289

I will change it back.

**Comment by 0x4007** [comment]
> @0x4007 That change was made after your request: https://github.com/ubiquity-os-marketplace/text-conversation-rewards/issues/92#issuecomment-2357720289
> 
> 
> 
> I will change it back.

We have come a long way in a few months.  

There were a lot of problems when that was posted and I suppose I figured that would have been the quickest solution to slightly more accurate scoring. These days I think the scoring is much more accurate. 

Semi related to that but relevance currently doesn't understand image contents, but with the new task I posted this should be solved. 
- https://github.com/ubiquity-os-marketplace/text-vector-embeddings/issues/58

**Comment by gentlementlegen** [comment]
@0x4007 you mean that when a user adds an image within a comment, it should also add some description within it? Like so?

<img width="106" alt="@0x4007 profile pic" src="https://github.com/user-attachments/assets/a4109ba7-fdeb-49e0-b492-039cea79bcc7" />

**Comment by 0x4007** [comment]
> @0x4007 you mean that when a user adds an image within a comment, it should also add some description within it? Like so?
> 
> 
> 
> <img width="106" alt="@0x4007 profile pic" src="https://github.com/user-attachments/assets/a4109ba7-fdeb-49e0-b492-039cea79bcc7" />
> 
> 

This should be discussed in the [dedicated task](https://github.com/ubiquity-os-marketplace/text-conversation-rewards/issues/215)
