### ISSUE TITLE
Change logs to use `ubiquity-dao/ubiquibot-logger`

### ISSUE THREAD

**Issue by gentlementlegen** [ubiquity-os-marketplace/command-wallet#4]
Currently the logs are handled manually with `console` messages. They should use our logger package to follow our usual display standards and logic.

https://github.com/ubiquity/ubiquibot-logger

C.f. https://github.com/ubiquibot/command-wallet/pull/2#discussion_r1668052899 and https://github.com/ubiquibot/command-wallet/pull/2#discussion_r1668051345

**Comment by wolfmic** [comment]
Since there is `context.logger.warn()` in two files (plugin.ts and command-parser.ts), should it be replaced with info method or should I wait until warn is getting implemented?

**Comment by gentlementlegen** [comment]
@wolfmic I think using `logger.error` instead of warn is fine for now.

**Comment by 0x4007** [comment]
@gentlementlegen @whilefoo can one bot be disabled now?

**Comment by gentlementlegen** [comment]
Marketplace needs both otherwise the runs won't work, you will get the `installation is disabled` error.
